version: '3.8'
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.12.1-management-alpine
    environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=mypass
    ports:
    # Rabbit mq instance
        - '5672:5672'
    # Web GUI
        - '15672:15672'